---
title: '**Bryn Haden's Resume**'
geometry: margin=2
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float:
      collapsed: true
      smooth_scroll: false
    includes:
      in_header: "favicon.html"
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

<style type="text/css">

div {
color: #13294B;
}

#TOC {
  color: #4B9CD3;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  color: #4B9CD3;
  background-color: #13294B;
}

a:link {
    color: #4B9CD3;
    text-decoration: none;
}

a:visited {
        text-decoration: none;
color: #4B9CD3;

}
a:hover {
color: #4B9CD3;
background-color: #13294B;
}

.main-container {
  max-width: 300px;
  margin-left: auto;
  margin-right: auto;
}

.column {
  float: left;
  width: 50%;
}

.row:after {
  content: "";
  display: table;
  clear: both;
} 

.center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 30%;
}

</style>

# **Overview** {.tabset}

I am a dedicated and detail-oriented professional with a strong background in data analysis, public health, and project management. With expertise in tools like Excel, Python, and Power BI, I excel at transforming complex datasets into actionable insights that drive decision-making and improve outcomes. I am seeking opportunities where I can contribute my analytical skills, technical expertise, and commitment to continuous improvement to support organizational goals, foster collaboration, and make a meaningful impact in fields such as healthcare, education, or sports analytics.

<div class="row">
  <div class="column">

- **Personal Information: [Bryn Haden](https://www.linkedin.com/in/bryn-haden-202522/)**
- Address: Carrboro, NC
- Contact Information:
    -Phone Number: 571-294-3588
    -Email: brynhaden@hotmail.com


# **Education** {.tabset}

## Undergraduate Education

- Roanoke College, B.S Health and Exercise Science & Public Health
    -2018-2022
    -GPA: 4.0/4.0
    -[Official Transcript](Git Hub Connections Here)

## - Graduate Education: Univeristy of North Carolina at Chapel Hill, MPH in Applied Epidemiology
    - 2023-2025
    - All High Passes or Passes
    - [Official Transcript] (Git Hub Connections Here gds/gdgs/Officla Transcript.pdf)

# **Relevant Experiences** {.tabset}

## Work Experiences

| Position Title | Organization | Location | Date | Job Duties |
|------|---------|--------:|---------:| ---------:|
|Implementation Research Assistant| North Carolina Institute for Public Health | Chapel Hill, NC | December 2023-Present| - Furthered the ongoing research of a literature review covering emergency response & planning documents for Region 4 of the United States -Created presentations and attended meetings with community partners within Region 4
-Assisted with preparation of meeting notes and agendas in advance of project meetings 
-Assisted with data collection and analysis tasks related to project implementation and evaluation
-Took courses on infodemiology to create social media monitoring reports for internal team 
-Assisted with preparation of final dissemination of workplan for CDC
-Supported planning efforts for implementation strategies selected in Year 1 of the Preparedness Center workplan through literature review, project team meetings, and partner meetings
-Contributed to the preparation of implementation materials to support state, local, territorial, and tribal health entities and their partners for selected strategies
|||||

## Internships

| Position Title | Organization | Location | Date | Job Duties |
|------|---------|--------:|---------:| ---------:|
|MAR 10| Spring Break | No Class ||
|MAR 12| Spring Break | No Class ||
|MAR 14| Spring Break | No Class ||
|APR 18| Well-being Day | No Class ||
|APR 25| Work on Championship | | |
|APR 28| Work on Championship | | |
|||||

## Other Work/Volunteer Experiences

| Position Title | Organization | Location | Date | Job Duties |
|------|---------|--------:|---------:| ---------:|
|MAR 10| Spring Break | No Class ||
|MAR 12| Spring Break | No Class ||
|MAR 14| Spring Break | No Class ||
|APR 18| Well-being Day | No Class ||
|APR 25| Work on Championship | | |
|APR 28| Work on Championship | | |
|||||


# **Skills, Publications/Presentations and Awards/Honors** {.tabset}

## Skills

Data Analysis Tools: R, REDCap, SAS, STATA, SPSS , Tableau, Microsoft Office Suite, Health Surveillance Database Management, Python, and R

-------

## Publications/Presentations

Haden, B., Iyer, K., Hartranft, L, & Ackley, E. I. (2022). Influence of perceived neighborhood food and physical activity environments 
on child weight trajectory. Southeast College of Sports Medicine Annual Meeting. Greenville, SC. [February 16-19, 2022]

Ackley, E. I., Iyer, K., & †Haden, B. (2021). Perceived neighborhood environments: Health impacts and catalysts for change. National Institutes of Health “Food Insecurity, Neighborhood Food Environment, and Nutrition Health Disparities: State of the Science 
Convening”. Virtual Workshop [September 21-23, 2021]

Haden, B., Iyer, K., & Ackley, E. I. (2021). Variations of obesity across the lifespan: Why zip code matters in the Roanoke Valley. 
Annual Meeting of the Virginia Public Health Association. Virtual meeting [April 9, 2021]

Iyer, K., Haden, B., & Ackley, E. I. (2021). Perceptions of neighborhood environments as a predictor of childhood obesity. Annual 
Meeting of the Virginia Public Health Association. Virtual meeting [April 9, 2021]

Publications: 
Haden, B., Steffan, S., & Ackley, E. I. (in progress). Data triangulation as a means to understand the impact of “place” on community 
health: A call to action in Appalachia. Journal of Appalachian Health. 

Iyer, K., Haden, B., & Ackley. E. I. (in progress). Identifying obesogenic neighborhoods: The utility of perceived access to healthy 
living resources. American Journal of Preventive Medicine

-------

## Awards/Honors

- Phi Beta Kappa Honors Society
- Roanoke College President’s List (2019 - 2022) 
- Academic All-American Finalist -Women’s Soccer (2021)
- Academic All-District – Women’s Soccer (2021)
- First Team-All ODAC Academic Team (2018-2021)
- ODAC All-State Academic Team (2022)
- Alpha Epsilon Delta Honors Society
- Alpha Lambda Delta Freshman Honors Society
- Department of Epidemiology Award (2024) 

-------

```

This page was last updated on `r Sys.time()` Eastern Time by Bryn Haden. The template for this website was created by [Mario Giacomazzo] (http://www.supermariogiacomazzo.com/).
